// @ts-nocheck
// --------------------------------------------------
// This file is auto-generated by Tuyau. Do not edit manually !
// --------------------------------------------------

import type * as types from '@tuyau/utils/types'
import type { InferInput } from '@vinejs/vine/types'

type ApiV1PingGetHead = {
  request: types.MakeTuyauRequest<
    InferInput<(typeof import('../app/controllers/ping_controller.ts'))['input']>
  >
  response: types.MakeTuyauResponse<
    import('../app/controllers/ping_controller.ts').default['handle'],
    true
  >
}
export interface ApiDefinition {
  api: {
    V1: {
      ping: {
        $url: {}
        $get: ApiV1PingGetHead
        $head: ApiV1PingGetHead
      }
    }
  }
}
const routes = [] as const
export const api = {
  routes,
  definition: {} as ApiDefinition,
}
